module/actor/actor.js
The `ActorStarfinder.applayDamage(roll, multiplier)` method wasn't setup correctly for starfinder. It would only apply damage to hit points and ignored stamina completely. This fixes that and now damage is applied properly.
=> Fixes damage application to follow starfinders rules

README.md, module/actor/actor.js, system.json
Quick hotfix for one issue and updates the manifest and README files.
=> Release v0.1.2

README.md, less/starship.less, module/actor/actor.js, module/item/item.js, starfinder.css, system.json
Also fixes an issue where wide images were incorrectly flexing and squishing the starship data.
=> Updates the system to work with v0.4.2+ of Foundry.

.gitignore, gulpfile.js, package-lock.json, package.json
=> Setting up a build process using gulp.

system.json
Updated `system.json` with new version.
=> Prepare for v0.1.6 release

system.json
I had the identifier for Japanese setup as `js` instead of `ja`. This fixes that.
=> Simple fix for localization.

src/module/actor/actor.js, src/module/combat.js, src/module/dice.js, src/module/item/item.js
This removes several deprecated foundry api calls that were removed in v0.6.0. This restores compatibility with the newer version of foundry.
=> Hot fix to remove deprecated foundry api calls.

src/module/classes/counter-management.js
Confirm not used files....sorry
=> Update the repo

src/module/rules.js, src/module/rules/actions/drone/calculate-chassis.js, src/module/rules/actions/drone/calculate-drone-defense.js
Forgot to include dexterity in the drone's AC calculations.
=> Fixed drone defense stat

src/lang/en.json, src/lang/fr.json, src/lang/ja.json
The drone sheet Owner field says "General Purpose Arms", it should instead say "Owner".
=> Drone Sheet Owner field has an invalid placeholder

src/module/rules.js, src/module/rules/actions/drone/calculate-chassis.js, src/module/rules/actions/drone/calculate-drone-saves.js
Con, Dex, and Wis scores weren't applied to saving throws.
=> Ability scores not applied to saves.

src/module/rules/actions/drone/calculate-drone-saves.js
There was a copy paste mistake in the calculation, my bad. :-)
=> Fix an error in drone saves

src/system.json
Hotfix to fix some copy paste issues.
=> Hotfix for the fix

src/lang/en.json, src/lang/fr.json, src/lang/ja.json, src/module/config.js
I noticed this one missing from immunities but it was required by some NPC or monster I was importing.
=> Added nonlethal as a damage type w/ localization

src/lang/en.json, src/lang/fr.json, src/lang/ja.json, src/less/actors.less, src/less/items.less, src/less/variables.less, src/module/actor/sheet/base.js, src/module/item/item.js, src/templates/actors/parts/actor-features-item.html, src/templates/actors/parts/actor-inventory-item.html
Mostly cosmetic changes for healing
=> Healing buttons

src/module/item/item.js, src/system.json
This is a hotfix release. This fixes #202
=> Hotfix for v0.6.0.0

src/lang/de.json, src/lang/en.json, src/lang/fr.json, src/lang/ja.json, src/module/combat/combat.js, src/module/config.js, src/module/item/item.js, src/module/item/sheet.js, src/module/rules.js, src/module/rules/actions/actor/calculate-save-modifiers.js, src/module/rules/actions/actor/calculate-skill-armor-check-penalty.js, src/module/rules/actions/actor/calculate-traits.js, src/module/settings.js, src/system.json, src/templates/actors/limited-sheet.html, src/templates/actors/starship-sheet.html
=> Bugfix release for starfinder

src/less/actors.less, src/less/apps.less, src/less/items.less
Fix for bold headers in item details
Match button shadows to their background colors
=> MinorGuiFixes

src/module/actor/sheet/vehicle.js, src/module/rules/actions/actor/vehicle/calculate-vehicle-passengers.js
Added migration step for vehicles created on previous versions (which would be missing `crew` object).
=> Add attacks to vehicles - migration step

src/items/alien-archives/glaiad.json, src/items/alien-archives/holofang.json, src/items/alien-archives/yrgytchee.json
Added the 3 aliens from the back of Fly Free or Die #2.
=> Added aliens for FFoD #2.

CONTRIBUTING.md, gulpfile.js
- Fixed a bug with cook validation, there was a mistake in my regular expressions for source.
- Various source fields now validated
- Armor type, race size, alien size now validated
- Weapon multi-attacks now validated
- Scans most biographies / descriptions for references to a Starfinder condition that doesn't have a link to the compendium
- Added an alternate cook command which skips formatting checks (they may be slower on older computers and you may just want access to the cooked data) 
- Updated CONTRIBUTING.md to mention the alternate cook command.
Cook will now check
=> Added vehicle,armor, spell & race validation. Added source field and condition link checking. Fixed bug with source validation.

src/system.json
Added the manifest+ authors section so all contributors can include info if they want.
=> Manifest+ Authors section

src/lang/pt-BR.json, src/system.json
A friend did the translation. Can you add it? Thanks!
=> Translation to Portuguese (Brazilian)

CONTRIBUTING.md
I missed this step. While obvious once pointed out to me,  it can't hurt to spell it out in my opnion.
=> Update CONTRIBUTING.md - Add new step

src/items/alien-archives/azer.json
This is my first pull request to a repo... So I am keeping this small just so I can get a feel of the process.
I have followed the [contributing doc link.](https://github.com/wildj79/foundryvtt-starfinder/blob/development/CONTRIBUTING.md#adding-new-items) 
Also, I tested the actor once it was done cooking and everything seemed in order.
I plan to go through and add the DoF items/NPCs if this works out.
Let me know if you see anything odd!
=> Add Azer from Dawn of Flames AP

src/module/config.js, src/module/item/item.js
Refactoring the additional attack modifiers to a getter, which would allow monkey-patching it so a module could let you edit the modifiers without making any other changes to rollAttack().
=> Refactor global attack modifier to a getter

src/items/alien-archives/mountain_eel.json
=> Add Mountain Eel

src/items/class-features/boundary_catalyst_(su).json, src/items/class-features/cascade_catalyst_(su).json, src/items/class-features/entropic_strike_(su).json, src/items/class-features/exergy_catalyst_(su).json, src/items/class-features/flashing_strikes_(ex)_(vanguard).json, src/items/class-features/inversion_catalyst_(su).json, src/items/class-features/invulnerability_(su).json, src/items/class-features/momentum_catalyst_(su).json, src/items/class-features/obsolescence_catalyst_(su).json, src/items/class-features/reaction_catalyst_(su).json, src/items/class-features/regression_catalyst_(su).json
Updated Entropic Strike damage
Updated Catalysts uses and saves
Updated Flashing strike's modifiers
Updated Invulnerability uses
=> Vanguard updates

src/lang/fr.json
Duplicate Weapon item instead of Wealth
=> Duplicate Weapon item instead of Wealth

src/less/actors.less, src/less/items.less, src/less/starship.less, src/less/vehicle.less
Without this some icons are missing entirely. Especially when hovering over features and such.
Fixes #560
=> Fix CSS image paths with route prefix

src/items/spells/summon_creature.json, src/lang/en.json, src/module/config.js
=> Add activation cost of Round

src/module/rules/actions/actor/character/calculate-base-armor-class.js
Fixes the 2nd half of #579. I'll try and figure out how proficiency detection works, but no promises on that. Feel free to merge this MR as it is.
=> Update shield dex cap paths

src/items/equipment/culinary_synthesizer_mk_2.json, src/items/equipment/culinary_synthesizer_mk_3.json
Quick fix; spotted the levels were all 1 on AoN, and the same was the case in the system.
=> Updated levels of mk 2 and 3 Culinary Synthesizer

changelist.md
Should be all of the ones missing
=> Update changelist with new merges

src/module/actor/sheet/base.js, src/module/item/item.js
The functions now give NPCs a formula based off of CR (because I could find no examples of an NPC with a CR different to their CL.) plus a general clean up.
=> Added NPC support to scaling cantrips

src/module/item/item.js
=> Allow chat card popout

src/less/actors.less, src/less/chat.less, src/less/items.less
=> Fix background repeating issues with certain class icons, plus wrapping long race text

src/items/tables/starship_critical_damage_effects.json
How did this not exist already? 🤣
Simple merge, just adds the starship crit effect table as a rolltable.
=> Add Starship Critical Damage Table

src/less/chat.less
This applies minor fix to make popout styling match that of the chat cards.
=> Fix popout styling

src/lang/de.json, src/lang/en.json, src/lang/fr.json, src/lang/it.json, src/lang/ja.json, src/lang/pt-BR.json, src/module/dice.js
As per [CRB pg. 240](https://aonsrd.com/Rules.aspx?ID=103), damage below 1 becomes 1 point of non-lethal damage. 
(This may rarely come up, but it may come up a bit more after by archaic -5 damage PR 😛)
=> Damage rolls below 1 return 1 non-lethal damage

src/lang/de.json, src/lang/en.json, src/lang/fr.json, src/lang/it.json, src/lang/ja.json, src/lang/pt-BR.json, src/module/config.js
=> DC ammo types

src/less/chat.less
=> Chat roll colors issue 457

CONTRIBUTING.md, scripts/README.md, scripts/data_entry/item_cleaner.js
Updated the Readme file for scripts to indicate what each script does and how to use them.
Also updated `item_cleaner.js` to make names closer adhere to the naming scheme of `gulfile.js`
=> Script UX and fixes

src/items/equipment/ability_crystal_(magic)_mk_1.json, src/items/equipment/ability_crystal_(magic)_mk_2.json, src/items/equipment/ability_crystal_(magic)_mk_3.json, src/items/equipment/synaptic_accelerators_mk_1.json, src/items/equipment/synaptic_accelerators_mk_2.json, src/items/equipment/synaptic_accelerators_mk_3.json, src/items/equipment/synergizing_symbiote_mk_1.json, src/items/equipment/synergizing_symbiote_mk_2.json, src/items/equipment/synergizing_symbiote_mk_3.json
Updated Descriptions for Personal Upgrades
Added Modifiers for Personal Upgrades
=> Personal Upgrades Update

src/module/item/item.js
NPCs still use the gunner's attack bonus as outlined [here](https://www.aonsrd.com/Rules.aspx?ID=551)
=> ECM starship weapons use Computers ranks + Int to hit

src/items/equipment/needler_rifle.json, src/items/spells/mystic_cure.json, src/items/spells/mystic_cure_mass.json
-Fix Needler Rifle AC #697 
-Fix Mystic Cure formulas
=> Data entry world 11-7-22

src/module/combat/combat.js
Closes #706 
Note this does add some `.data.data`s, could refactor to target V10 now if needed
=> Correct starship initiative formula to include modifiers to piloting

src/templates/actors/parts/actor-features-item.html, src/templates/actors/parts/actor-inventory-item.html
=> Restore usage buttons

src/module/actor/sheet/base.js
Closes #766 
This has actually been a bug for a while 😉
=> Fix missing add spell button if all spells are innate/always available

src/module/item/item.js
Currently the attack bonus box on starships doesn't work
Closes #728
=> Fix Starship weapon attack bonus box

src/less/chat.less
=> Fix broken headings on chat cards

src/module/canvas.js
=> Fix NaN on 5/5/5 ruler for V10

src/module/item/sheet.js
=> Fix opening ASI sheets

src/module/actor/sheet/npc.js, src/templates/actors/npc2-sheet.html
=> Restore NPC biography

src/items/alien-archives/anacite_wingbot.json
Updated Anacite wingbot with appropriate speed.
Also updated feat to display save DC, and added modifier for bonus to Climbing.
Fixes #782
=> Updated Anacite wingbot

src/items/class-features/entropic_strike_(su).json
Updated Entropic Strike to weapon item.
Updated to V10.
=> Updated Entropic Strike

src/templates/actors/hazard-sheet-full.html, src/templates/actors/hazard-sheet-limited.html, src/templates/actors/parts/actor-biography.html, src/templates/actors/starship-sheet-full.html, src/templates/actors/starship-sheet-limited.html, src/templates/actors/vehicle-sheet-full.html, src/templates/actors/vehicle-sheet-limited.html, src/templates/items/parts/item-description.html
=> Update actor sheet editors to use prosemirror

src/items/races/tromlin_bloodseeker.json, src/items/races/tromlin_hardshell.json, src/items/racial-features/armor_talent.json, src/items/racial-features/blood_scent.json, src/items/racial-features/carrier.json, src/items/racial-features/head_frill.json, src/items/racial-features/jumper_(tromlin_bloodseeker).json, src/items/racial-features/natural_quadruped.json, src/items/racial-features/pounce.json, src/items/racial-features/powerful_charge.json, src/items/racial-features/slow_biped.json, src/items/racial-features/unarmed_strike_(horns).json, src/items/racial-features/unarmed_strikes_(bite_and_claws).json
Added Tromlin races and Racial features.
=> Tromlin Races

src/items/classes/biohacker.json, src/items/classes/envoy.json, src/items/classes/mechanic.json, src/items/classes/mystic.json, src/items/classes/nanocyte.json, src/items/classes/operative.json, src/items/classes/precog.json, src/items/classes/solarian.json, src/items/classes/soldier.json, src/items/classes/technomancer.json, src/items/classes/vanguard.json, src/items/classes/witchwarper.json, src/module/rules/actions/actor/calculate-classes.js
This will require all future classes to have a slug if they are to be localised properly. I will explore options for automatic slug generation.
Closes #799
=> Ensure localised class names still play nice with modifiers

src/lang/de.json, src/lang/en.json, src/lang/fr.json, src/lang/it.json, src/lang/ja.json, src/lang/pt-BR.json, src/less/actors.less, src/less/apps.less, src/less/variables.less, src/module/settings.js, src/sfrpg.js
-SFRPG custom theme: changes Foundry's colour scheme to blue and changes the pause and Foundry logo to SFRPG themed icons
-Added line-height to links to improve readability
-Fixed long starship frame names overflowing
-Added a dashed indicator on embedded items
-Maintain aspect ratio on character art
-Fixed a few fonts not being the SFRPG font
=> Implement various CSS fixes, and a new theme

src/module/item/item.js
=> Apply spell damage modifiers to saving throw spells

src/less/actors.less
=> Change height attribute on attributes to min-height

src/module/rules.js, src/module/rules/actions/actor/calculate-class-dc.js, src/module/rules/actions/actor/calculate-classes.js
`@classes.[classname].classDC` will return the standard ability DC using that class's levels and KAS (10 + 1/2 level + KAS). Also featuring some ESlint cleanup of files
=> Add a new roll data attribute for a class's ability DC

src/module/actor/actor.js, src/module/apps/edit-skill-dialog.js, src/templates/apps/add-edit-skill.html
Also adjusted their UI a bit to make editing them a bit more intuitive
ESLint cleanup continues
=> Fix skill notes not including actor roll data

src/less/character.less, src/module/actor/sheet/base.js, src/module/config.js, src/templates/actors/character-sheet.html
- added skill compendium links
looks like this (as requested only the book leads to the compendium):
=> skill compendium links

src/items/spells/energy_ray.json, src/items/spells/hazard.json, src/items/spells/injury_echo.json, src/items/spells/telekinetic_projectile.json, src/module/actor/sheet/base.js, src/module/item/item.js, src/module/settings.js
-Add damage sections for each damage type, all part of the same group, to all damaging cantrips
-Migrated the scaling functions to static methods on the ItemSFRPG class for organisation's sake
=> Scaling cantrip settings account for multiple damage sections

src/templates/actors/parts/actor-inventory-item.html
Currently the open/close button font is incorrect
=> Fix container open/close button font

gulpfile.js
=> Remove some needless awaits from gulpfile.js

src/module/actor/mixins/actor-damage.js, src/templates/actors/character-sheet.html
- fixed temp hp
Fixes https://github.com/foundryvtt-starfinder/foundryvtt-starfinder/issues/848
=> temp hp damage calculation

src/module/actor/actor.js, src/module/utils/compendium-art.js, src/module/utils/is-object.js, src/sfrpg.js
=> Implement applying art to compendiums from modules

src/items/spells/embrace_of_the_void.json
=> Fix embrace the void formula

src/module/config.js, src/module/packs/alien-archive-browser.js, src/module/packs/browsers.js, src/module/packs/document-browser.js, src/module/packs/equipment-browser.js, src/module/packs/pack-loader.js, src/module/packs/spell-browser.js, src/module/packs/starship-browser.js, src/templates/packs/document-browser.hbs
Current known issue is that entries only drag and drop after the second attempt, not the first
=> Refactor compendium browsers to use indexes

src/lang/de.json, src/lang/en.json, src/lang/fr.json, src/lang/it.json, src/lang/ja.json, src/lang/pt-BR.json, src/less/actors.less, src/module/actor/sheet/base.js, src/module/packs/spell-browser.js, src/sfrpg.js, src/templates/actors/parts/actor-features.hbs, src/templates/actors/parts/actor-inventory.hbs, src/templates/actors/parts/actor-spellbook.hbs
- added pre filtered compendium browser buttons to actorsheet (inventory and spellbook)
- added handlebars helper for lazy people like me to debug templates easier
- added some localization text
Some more frontend related people might want to check the button styling. I have now idea how to make that look good
=> compendium browser buttons for actorsheet

src/module/actor/sheet/base.js, src/module/actor/sheet/character.js, src/module/actor/sheet/drone.js, src/module/actor/sheet/hazard.js, src/module/actor/sheet/npc.js, src/module/actor/sheet/starship.js, src/module/actor/sheet/vehicle.js
- GM Notes on NPCs now shows. Closes #879 
- Drone biography/GM notes now show
- Refactor to put re-used fields on the base sheet class
=> Fix some actor bios not rendering

src/items/spells/blessing_of_youth.json
Fixed Blessing of Youth's formula
#888
=> Blessing of Youth

src/module/actor/sheet/hazard.js, src/module/dice.js
=> Fix hazard damage rolls

src/items/spells/adamantine_shot.json, src/items/spells/death's_door.json
Also fixed lookupRanges to not flood chat, and change Death's Door icon to be more death-y
=> Replaced all instances of @data.level with @item.level

src/sfrpg.js
=> Ensure compatibility with modules that alter the pause icon

src/lang/de.json, src/lang/en.json, src/lang/fr.json, src/lang/it.json, src/lang/ja.json, src/lang/pt-BR.json, src/module/apps/roll-dialog.js, src/module/dice.js, src/module/item/item.js, src/module/rolls/roll.js, src/templates/chat/roll-dialog.hbs
This replaces ugly lookupRanges on roll dialogs with the resolved formula
=> Display simplified formulas on roll dialogs

src/module/packs/pack-loader.js
=> Fix armor filtering in compendium browser

src/module/actor/actor.js, src/module/item/item.js
Reverts foundryvtt-starfinder/foundryvtt-starfinder#911
=> Revert "Update object population to use the correct SFRPG object"

src/module/actor/actor-inventory-utils.js, src/module/item/mixins/item-capacity.js
=> Fix some aliens being unable to open

src/items/racial-features/daredevil.json, src/items/racial-features/exceptional_vision.json, src/items/racial-features/honey_production.json
=> Removed/edited incorrect Skilled modifiers

src/lang/de.json, src/lang/en.json, src/lang/fr.json, src/lang/it.json, src/lang/ja.json, src/lang/pt-BR.json, src/module/actor/actor.js, src/module/actor/sheet/base.js, src/module/actor/sheet/character.js, src/templates/actors/parts/actor-features-item.hbs
I did a thing. Looks like this:
Only shown if you have enough XP.
You press it -> the according class levels up.
=> level up button for classes

src/less/sheets.less
Now these are the features I really care about 😎
=> Round the bottom sheet corners

src/sfrpg.js
Ternaries make a better, more terse, alternative to lookupRanges in particularly simple formulas.
E.g `ternary(gte(5,3), 20, 10)` -> 20
=> Refactor math functions and implement ternary operator

src/items/spells/quick_change_(galactic_magic).json
=> Quickly change for Quick Change

src/less/sheets.less, src/module/rules/actions/actor/calculate-class-dc.js, src/template.json
This was a strange set of circumstances
=> Fix new classes bricking the character sheet lmao

src/items/class-features/entropic_strike_(su).json
fixed new damage addition to be ceil instead of floor.
=> Quick update to entropic Strike

src/items/equipment/inferno_knife.json
Addresses #974 
In addition, gave knife 0/12 usage for petrol tracking (5 minute intervals for the hour total)
=> Updated inferno_knife

src/sfrpg.js
I must be going soft, implementing features to satisfy modules... (Only because I plan to use it myself in an upcoming campaign 😛)
Closes #802 
Also PR 1000! 🎉
=> Defer to creating Item Piles loot tokens if enabled

src/less/items.less
This removes the scrollbar that seems to appear on all items
=> Remove needless padding on item sidebars

src/module/item/item.js
=> Ensure existing class slugs are used

src/items/equipment/cunning.json, src/items/equipment/scalegraser_asp-series.json, src/items/equipment/scalegraser_cobra-series.json, src/items/equipment/scalegraser_python-series.json, src/items/equipment/scalegraser_viper-series.json
Added scalegraser weapons and the cunning weapon fusion.
=> Added Scalegraser weapons and Cunning weapon fusion

src/lang/de.json, src/lang/en.json, src/lang/fr.json, src/lang/it.json, src/lang/ja.json, src/lang/pt-BR.json, src/module/actor/sheet/base.js, src/module/dice.js, src/module/item/item.js, src/sfrpg.js, src/templates/chat/consumable-card.hbs
Also fixes issues with consumables not decreasing, and some object Object on consumable cards
=> Allow dragging item buttons to the macro bar to create quick access macros

src/less/apps.less, src/module/system/enrichers/base.js, src/module/system/enrichers/browser.js, src/module/system/enrichers/check.js, src/sfrpg.js
=> Refactor check listeners, and apply hex background to journals

src/items/equipment/medkit_advanced.json, src/items/equipment/medpatch.json
=> Small med update.

src/template.json
Plus a format of template.json
Closes #1016
=> Ensure NPCs actually have no stamina

src/module/item/sheet.js
Fixes: https://github.com/foundryvtt-starfinder/foundryvtt-starfinder/issues/1027
=> fixed item hardness calculation

src/items/feats/versatile_specialization_(combat).json, src/items/feats/weapon_focus_(combat).json
=> updated versatile specialization and weapon focus

src/module/actor/actor.js, src/module/classes/floating-number-menu.js
-Promise all setting settings from the floaty numbers config window
-Use `items.get` for class level ups rather than iterating over the items array to fish out the class item.
=> Minor performance improvements

src/lang/de.json, src/lang/en.json, src/lang/fr.json, src/lang/it.json, src/lang/ja.json, src/lang/pt-BR.json, src/module/item/item.js, src/sfrpg.js
=> Fix popped out chat cards listeners

src/sfrpg.js
=> Escape user inputted create tippy data

src/module/actor/actor.js, src/module/rules/closures/stack-modifiers.js
=> Fix number-y modifiers, and item creation sometimes failing

src/less/actors.less, src/module/actor/sheet/base.js, src/module/actor/sheet/character.js, src/module/actor/sheet/drone.js, src/module/actor/sheet/npc.js, src/module/actor/sheet/starship.js, src/module/actor/sheet/vehicle.js, src/module/item/item.js, src/module/item/sheet.js, src/sfrpg.js, src/templates/actors/parts/actor-features-item.hbs, src/templates/actors/parts/actor-inventory-item.hbs, src/templates/actors/starship-sheet-full.hbs
Reverts foundryvtt-starfinder/foundryvtt-starfinder#975
=> Revert "Show weapon attack and damage values on buttons"

src/module/actor/actor.js, src/module/rules/closures/stack-modifiers.js
Reverts foundryvtt-starfinder/foundryvtt-starfinder#1069
=> Revert "Fix number-y modifiers, and item creation sometimes failing"

src/module/actor/actor.js, src/module/rules/closures/stack-modifiers.js
Reverts foundryvtt-starfinder/foundryvtt-starfinder#1071
=> Revert "Revert "Fix number-y modifiers, and item creation sometimes failing""

src/less/actors.less, src/module/actor/sheet/base.js, src/module/actor/sheet/character.js, src/module/actor/sheet/drone.js, src/module/actor/sheet/npc.js, src/module/actor/sheet/starship.js, src/module/actor/sheet/vehicle.js, src/module/item/item.js, src/module/item/sheet.js, src/sfrpg.js, src/templates/actors/parts/actor-features-item.hbs, src/templates/actors/parts/actor-inventory-item.hbs, src/templates/actors/starship-sheet-full.hbs
Reverts foundryvtt-starfinder/foundryvtt-starfinder#1070
=> Revert "Revert "Show weapon attack and damage values on buttons""

src/sfrpg.js
This fixes the weird warping when the Anvil painfully mutates into the SF logo.
=> Wait for SF logo to load before switching FVTT Anvil logo

src/module/packs/alien-archive-browser.js, src/module/packs/document-browser.js, src/module/packs/equipment-browser.js, src/module/packs/spell-browser.js, src/module/packs/starship-browser.js, src/templates/items/augmentation.hbs, src/templates/packs/document-browser.hbs
In theory Maps are faster to load and use less memory. Filtering is also noticeably faster.
Downside is we have to do janky stuff in handlebars. Could add a new helper to make it cleaner?
=> Use Maps to load compendium browsers rather than Arrays

src/less/actors.less, src/less/apps.less, src/less/canvas.less, src/less/character.less, src/less/chat.less, src/less/document-browser.less, src/less/drone.less, src/less/items.less, src/less/limited.less, src/less/npc.less, src/less/roll.less, src/less/starship.less, src/less/variables.less, src/less/vehicle.less
This allows the core Font Size setting to affect SFRPG sheets and apps
=> Use foundry font-size variables instead of raw px sizes

src/lang/de.json, src/lang/en.json, src/lang/fr.json, src/lang/it.json, src/lang/ja.json, src/lang/pt-BR.json, src/less/actors.less, src/less/npc.less, src/module/actor/sheet/npc.js, src/module/config.js, src/sfrpg.js, src/template.json, src/templates/actors/npc2-sheet.hbs, src/templates/actors/parts/actor-traits.hbs
=> Show Combat Role on NPCs

src/module/actor/sheet/base.js
=> Fix crossed wires with source and target actors in drag-drop processing

src/items/creature-companions/pot-bellied_bulette.json
Added Pot-bellied Bulette creature Companion
=> PoC Creature Companion

src/items/class-features/adaptive_strike_(ex)_(melee).json, src/items/class-features/evolution_track_(su).json
Added Str to damage formulas for Adaptive Strike (Melee)
Added automated modifiers to Evolutionist Track
=> Fixed and updated some Evolutionist features

src/templates/apps/modifier-app.hbs
The modifier system is more robust than I give it credit for.
=> Add blank skill modifier value

src/items/feats/group_negotiations.json, src/items/feats/improved_supporting_fire_(combat).json, src/items/feats/spot_structural_vulnerability.json, src/items/feats/take_this.json
Remaining feats to AP-38, the others of which are added in #1137
=> Added missing feats from AP-38

src/module/actor/sheet/base.js, src/module/dice.js, src/module/item/item.js, src/module/rules/actions/actor/calculate-ability-check-modifiers.js, src/module/rules/actions/actor/calculate-actor-resources-early.js, src/module/rules/actions/actor/calculate-actor-resources-late.js, src/module/rules/actions/actor/calculate-armor-modifiers.js, src/module/rules/actions/actor/calculate-bab-modifier.js, src/module/rules/actions/actor/calculate-base-ability-modifier.js, src/module/rules/actions/actor/calculate-base-ability-score.js, src/module/rules/actions/actor/calculate-cmd-modifiers.js, src/module/rules/actions/actor/calculate-encumbrance.js, src/module/rules/actions/actor/calculate-initiative-modifiers.js, src/module/rules/actions/actor/calculate-movement-speeds.js, src/module/rules/actions/actor/calculate-save-modifiers.js, src/module/rules/actions/actor/calculate-skill-modifiers.js, src/module/rules/actions/actor/character/calculate-hitpoints.js, src/module/rules/actions/actor/character/calculate-resolve.js, src/module/rules/actions/actor/character/calculate-skill-armor-check-penalty.js, src/module/rules/actions/actor/character/calculate-skillpoints.js, src/module/rules/actions/actor/character/calculate-stamina.js, src/module/rules/actions/actor/drone/calculate-drone-hitpoints.js, src/module/rules/actions/actor/drone/calculate-drone-resolve.js, src/module/rules/actions/actor/npc2/calculate-npc2-abilities.js, src/module/rules/closures/stack-modifiers.js
- fixed modifiers being broken on compendium actors
=> Hotfixes for the new modifier system.

src/items/class-features/sniper.json
Fixes Sniper alternate class feature #1088
=> Updated Sniper feature

src/items/equipment/speed_suspension_complete.json, src/items/equipment/speed_suspension_minimal.json, src/items/equipment/speed_suspension_standard.json
Updated Speed Suspension's modifiers bonus type to Enhancement
=> Speed Suspension update

src/module/item/item.js
Closes #299 
Closes #579
Closes #586
=> Auto set weapon/shield proficiency when adding an item to a PC

src/items/starship-actions/target_system.json
=> add sensor bonus to target action

src/items/starships/oliphaunt.json
fix incorrect starship frame for oliphaunt #1169
=> Use correct starship frame in oliphaunt

src/templates/actors/parts/actor-modifiers.hbs
I've never been so angry to solve a bug 😂
Closes #1168
=> Fix potential race condition in condition toggling

src/less/actors.less, src/module/apps/trait-selector.js, src/module/item/sheet.js, src/templates/items/starshipPowerCore.hbs
=> Fix power core supported sizes

src/module/actor/actor.js, src/module/actor/mixins/actor-damage.js
If damage reduces HP and SP, both will show.
=> Allow multiple HP/SP diffs to render floaters

src/lang/de.json, src/lang/en.json, src/lang/fr.json, src/lang/it.json, src/lang/ja.json, src/lang/pt-BR.json, src/less/items.less, src/module/item/item.js, src/module/item/sheet.js, src/module/rolls/rolltree.js, src/templates/items/parts/item-action.hbs
This is a plaster on top of a plaster and I don't like this, but fuck it
Closes #1200
=> Implement primary damage section toggle to limit modifiers to one damage section per weapon

src/module/apps/roll-dialog.js, src/templates/items/parts/item-action.hbs
-Set "for" for primary section labels
-Fix submitting roll dialog on enter
=> Roll dialog fixes

src/lang/en.json, src/module/apps/spell-cast-dialog.js, src/templates/apps/spell-cast.hbs
-Default casted level to spell's level (Closes #664)
-Fix undefined spell name (Closes #1177)
=> Spell Dialog fixes

src/lang/de.json, src/lang/en.json, src/lang/fr.json, src/lang/it.json, src/lang/ja.json, src/lang/pt-BR.json, src/module/item/item.js, src/templates/items/parts/item-action.hbs
Some hideous logic to set default primary groups on items with damage groups
=> Primary damage groups

changelist.md, src/lang/de.json, src/lang/en.json, src/lang/fr.json, src/lang/it.json, src/lang/ja.json, src/lang/pt-BR.json, src/less/actors.less, src/module/actor/actor.js, src/module/actor/sheet/base.js, src/module/apps/modifier-app.js, src/module/modifiers/modifier.js, src/module/rules/actions/actor/character/calculate-base-skills.js, src/module/rules/closures/stack-modifiers.js, src/module/system/settings.js, src/module/token/tokendocument.js, src/system.json
Fix various modifier bugs in 0.25
=> Prepare for 0.25.1

changelist.md, src/lang/de.json, src/lang/en.json, src/lang/fr.json, src/lang/it.json, src/lang/ja.json, src/lang/pt-BR.json, src/less/actors.less, src/module/actor/actor.js, src/module/actor/sheet/base.js, src/module/apps/modifier-app.js, src/module/modifiers/modifier.js, src/module/rules/actions/actor/character/calculate-base-skills.js, src/module/rules/closures/stack-modifiers.js, src/module/system/settings.js, src/module/token/tokendocument.js, src/system.json
* 0.25 hotfixes
* More fixes
* Manifest and changelog
=>  0.25.1 (#1245)

src/lang/de.json
Very small pull request to translate the latest additions in 0.25.2 into German.
=> De translation of damage groups and warning

src/module/actor/actor.js, src/templates/apps/spell-cast.hbs
Change Spell dialogue to use spell level rather then an index
fixes #1267
=> Changes for spell slot selection #1267

src/less/items.less
=> Fix text wrapping on properties/descriptors

src/template.json
=> Set default spell uses to null

src/items/class-features/avenging_burst_(mechanized_niche).json, src/items/universal-creature-rules/invisible.json, src/lang/en.json, src/module/item/item.js, src/module/migration.js, src/module/system/item-macros.js, src/sfrpg.js
Also add spellcasting dialog to spell item macros, and fix Avenging Burst formula
Closes #1329
Closes #1327 
Closes #1325
=> Fix migrations for V12, and an error from the UCR pack

src/items/races/alkainan.json, src/items/racial-features/metallic_bloodline.json, src/items/racial-features/metallic_bloodline_(ferrous).json, src/items/racial-features/metallic_bloodline_(nonferrous).json, src/items/racial-features/metallic_bloodline_(skymetal).json, src/items/racial-features/natural_weapons.json
=> Alkainan species

src/templates/apps/item-collection-sheet.hbs
=> container scrolling hack

src/module/item/sheet.js
=> Starship Weapon "Not Mounted" localization key typo

src/items/equipment/dragon_rifle_wyrmling.json, src/items/starship-components/booster_thruster_housing.json, src/items/starship-components/holographic_mantle.json
=> Some typos in item names and sources

src/items/alien-archives/planar_scion_ifrit.json
=> Added Fire Resistance species feature to Planar Scion, Ifrit

src/items/starship-components/huge_starship_monstrous_humanoid.json, src/items/starship-components/large_starship_monstrous_humanoid.json, src/items/starships/swarm_dreadlancer.json, src/items/starships/swarm_gnawbore.json
=> Swarm Dreadlancer

src/items/alien-archives/dirindi_fabulist.json
=> Dirindi Fabulist typo fix

src/items/class-features/unleash_magic_(sp).json
=> #1302 formula fix for Unleash Magic save throw

src/lang/fr.json
Added translations for new keys that were not yet translated.
=> Added translations for new keys

src/items/alien-archives/pyric_harbinger.json, src/items/alien-archives/pyric_heliacus.json, src/items/alien-archives/pyric_revenant.json, src/items/alien-archives/pyric_wraith.json
=> Pyric Curse enrichment and fixes

CONTRIBUTING.md, data-sources.md
Updated the list of sources on the contributing file to include the most recent set of hardcover releases, and to reorder books so they are in chronological release order.
=> Update data source codes and formatting for contributors

src/template.json, src/templates/items/theme.hbs
Resolves #1382, and will allow #1377 and/or #1319 to have data input correctly
=> allow blank theme skill and attribute to be selected

src/module/actor/actor.js, src/module/actor/mixins/actor-rest.js, src/module/actor/sheet/vehicle.js, src/module/chat/chatbox.js, src/module/combat/combat.js, src/module/dice.js, src/module/item/item.js, src/module/item/mixins/item-activation.js, src/module/item/mixins/item-capacity.js, src/module/rolls/roll.js
Small tweak to fix roll visibility settings not being set from the dialog boxes correctly
=> fix roll mode not set properly from dialog box

src/module/rules/actions/actor/calculate-bulk-and-wealth.js, src/templates/actors/parts/actor-inventory-item.hbs
=> Display calculated bulk of containers whose contents don't affect encumbrance on actor sheets

changelist.md, src/lang/de.json, src/lang/en.json, src/lang/fr.json, src/lang/it.json, src/lang/ja.json, src/lang/pt-BR.json
I've run `copyLocalization` to clean up the localizations, and added to changelist.md a full list of the changes made to the system for v0.27.0
=> v0.27.0 pre-release tasks

src/items/alien-archives/alkainan.json, src/items/alien-archives/bloodseeker_trooper_(tromlin).json, src/items/alien-archives/gathol.json, src/items/alien-archives/hardshell_defender_(tromlin).json, src/items/alien-archives/luminix.json, src/items/alien-archives/mi-go_high_priest.json, src/items/alien-archives/morlamaw_mayor.json, src/items/alien-archives/planar_scion_ganzi.json, src/items/alien-archives/planar_scion_prismeni.json, src/items/alien-archives/trox_defensor.json, src/items/alien-archives/varratana.json
Found some references in Alien archives entries.
=> Adding .Item to Compendium references

src/system.json
=> Add hot reload and re-arrange system.json

src/items/spells/caustic_fissure.json
https://aonsrd.com/SpellDisplay.aspx?ItemName=Caustic%20Fissure
=> Add Caustic Fissure

src/module/packs/alien-archive-browser.js, src/module/packs/document-browser.js, src/module/packs/spell-browser.js, src/module/packs/starship-browser.js
Before getting items from a compendium pack, check whether the current user has permissions to view the pack.
Closes #702
=> Browser permissions fix

src/system.json
=> Remove the `v` from version number in system.json

src/module/item/item.js
=> Allow tracking starship weapons without charges to still fire

src/module/actor/mixins/actor-modifiers.js, src/module/actor/sheet/base.js, src/module/actor/sheet/drone.js, src/module/apps/modifier-app.js, src/module/item/item.js, src/module/item/sheet.js, src/module/modifiers/modifier.js
`modifier.parentUpdate` applies the changes to the modifier and updates it within its parent. This saves you having to fumble around with arrays every time.
Untested so draft for now. Feel free to test/modify/merge at your leisure though
=> Move various methods related to modifiers to the Modifier class, and add new helpers to make updates and deletions easier

src/items/alien-archives/ferrofluid_ooze.json, src/items/characters/keskodai_l1.json, src/items/characters/keskodai_l8.json, src/items/class-features/nanite_surge_(ex).json, src/items/spells/dampen_spell.json, src/items/spells/puncture_veil.json, src/items/vehicles/cherav.json
This is a compilation PR to fix a bunch of minor compendium issues
=> Fix minor compendium issues

src/items/alien-archives/detective.json, src/items/alien-archives/gang_pusher.json, src/items/alien-archives/mercenary_commando.json, src/items/characters/iseph_l1.json, src/items/characters/iseph_l4.json, src/items/characters/iseph_l8.json, src/items/class-features/trick_attack_(ex).json, src/items/class-features/trick_attack_(ex)_(heavyweight_skirmisher).json, static/lang/en.json
A few miscellaneous fixes for minor typos that I've found while playing Starfinder.
=> Miscellaneous typo fixes

build/package.js, package-lock.json, package.json, vite.config.js
#1547
Also, added esbuild in dev dependencies explicetly
=> Ensure that dist directory exists on a build step

src/items/equipment/vidgame_basic_vr_starfighter_frenzy.json
Fixes one item with an incorrect system version that keeps getting caught in the unpack/cook process
=> Fix one item with wrong version number

CONTRIBUTING.md, changelist.md, data-sources.md
Updates to the changelist, data sources, and contributing file for Starfinder v28, Foundry v13.
=> Changelist v28

src/items/alien-archives/psycopomp_erabryth.json, src/items/alien-archives/psycopomp_morrigna.json
=> Psychopomp spelling fix

src/items/spells/day's_weariness.json
=> Day's weariness' damage changes

src/items/class-features/apocalypse_insight_(ex).json
=> Apocalypse Insight description fix

changelist.md
Fixes for some minor compendium issues added to changelog
=> updates due to compendium fixes

README.md
Made some updates to the readme to reflect changes made to the release system. Also made clearer the preferred installation method(s) and when to use each.
Closes #1566
=> Update README.md for installation method

build/lib/level-database.js, build/unpack.js, src/module/dice.js, src/module/packs/document-browser.js, src/module/packs/equipment-browser.js, vite.config.js
- Compact LevelDB files
- Correct unpack input folder
- Minify CSS again
- Some typings
=> Compact LevelDB files during cook, and re-enable CSS minification

src/module/actor/actor.js, src/module/actor/sheet/base.js, src/module/actor/sheet/hazard.js, src/module/actor/sheet/starship.js, src/module/actor/sheet/vehicle.js, src/module/apps/choice-dialog.js, src/module/apps/drone-repair-dialog.js, src/module/apps/edit-skill-dialog.js, src/module/apps/input-dialog.js, src/module/apps/item-collection-sheet.js, src/module/apps/item-deletion-dialog.js, src/module/apps/npc-skill-toggle-dialog.js, src/module/apps/short-rest.js, src/module/apps/spell-cast-dialog.js, src/module/apps/trait-selector.js, src/module/chat/chatbox.js, src/module/classes/counter-management-windows.js, src/module/combat/combat.js, src/module/item/item.js, src/module/item/mixins/item-activation.js, src/module/item/mixins/item-capacity.js, src/module/item/sheet.js, src/module/rolls/roll.js
This fixes some instances where foundry functions were being referenced by their deprecated global versions. Modern namespacings are added to refer to these functions.
=> V13 namespace updates

src/module/actor/sheet/base.js, src/module/item/sheet.js, static/lang/de.json, static/lang/en.json, static/lang/fr.json, static/lang/it.json, static/lang/ja.json, static/lang/pt-BR.json, static/templates/actors/parts/actor-inventory.hbs, static/templates/items/parts/item-description.hbs
Resolves #501.
I've added support for delta input values to both of these fields, as well as adding a tooltip identifying that this is possible.
=> Support delta (+/-) input on item quantity and actor currency fields

src/module/actor/actor.js, src/module/dice.js, src/module/item/item.js, src/module/rolls/rolltree.js
3ade256f1e444d972eb24b2b43eb27ad5d9ceb45 broke someone's macros. On reflection, expecting those methods to return values is reasonable, so let's provide a proper API for it.
closes #1600
=> Return RollResult objects from Actor/Item roll methods

static/lang/es.json, static/system.json
Adds Spanish translation generously submitted by @GusRPG in https://github.com/foundryvtt-starfinder/foundryvtt-starfinder/discussions/1608
=> Adds Spanish translation by GusRPG

static/system.json
=> Update verified foundry version

src/module/actor/sheet/base.js
=> Allow decimals in currency value sanitization

src/items/starships/atech_immortal.json
=> Fixes for the Atech Immortal

src/items/racial-features/cultural_fascination.json
Cultural Fascination incorrectly has a Standard Action, this PR removes it.
=> Remove standard action from Cultural Fascination

src/items/equipment/plasma_guide_series-21.json, src/items/equipment/plasma_guide_series-28.json, src/items/equipment/plasma_guide_series-37.json, src/items/equipment/plasma_guide_series-42.json, src/items/equipment/plasma_guide_series-62.json, src/items/equipment/plasma_guide_series-73.json
The plasma guide items are missing their description. This PR adds it.
=> Add description to plasma guide items
