- src/module/actor/sheet/starship.js
Dragging previously added crew members to a new role after reloading or restarting the application (for example when starting a new gaming session) throws the following error and you can't change roles.
`starship.js:355 Uncaught TypeError: Cannot read property 'id' of null
at ActorSheetStarfinderStarship._onDragCrewStart (starship.js:355)`
For some reason the Actor **_token_** is being referenced (which is not always available) when the `actorId `is already available in a constant in the same function. This small change fixes that bug so that reassigning crew members always works.
> Fix: Dragging crew members to new roles throws an error

- src/less/items.less
- src/module/actor/actor.js
- src/module/actor/sheet/character.js
- src/module/item/item.js
- src/module/item/sheet.js
- src/module/templates.js
- src/templates/items/archetypes.html
- src/templates/items/augmentation.html
- src/templates/items/class.html
- src/templates/items/equipment.html
- src/templates/items/feat.html
- src/templates/items/parts/item-modifiers.html
- src/templates/items/race.html
- src/templates/items/theme.html
- src/templates/items/weapon.html
Updated modifiers system for player characters:
* Added support for child modifiers from items.
* Added modifiers to the sheets of archetypes, augmentations, classes, equipment, feats, races, themes, and weapons.
* Added passing of child modifiers to closures.
* Removed Item and Misc categories from character modifiers sheet.
> Added support for child modifiers

- src/module/actor/sheet/base.js
- src/templates/actors/parts/actor-inventory.html
A minor QoL thing that is helpful for many players, this adds a checkbox to the inventory screen for weapons and equipment. This will also affect closures that respond to the item modifiers, once the child modifiers pull request goes through.
> QoL: Easy Equipping

- src/lang/en.json
It says swfit action, should say swift action. Caught by cmd.
> Invalid text for swift action

- src/module/config.js
Misspelling and mismatch in keys in some of the configuration arrays was causing issues with conditions.
> Fix for broken conditions

- src/module/rules/actions/actor/calculate-base-armor-class.js
- src/module/rules/actions/actor/calculate-skill-armor-check-penalty.js
In the tooltip below you see two shields with different names. "1st shield" has proficiency checked but "2nd shield" does not. They are otherwise identical.
> AC calculations now correctly handle multiple shields equipped at the same time

- src/template.json
Small tweak which adds default `save` object to `Vehicle Attack` type items. This wasn't needed for 0.7.9 but seems like it's probably a good pattern to maintain as other objects with saves provide a similar default object, and prevents a migration step which would be required on updating to 0.8.0 (based on current state of alpha).
> Future proofing/add default save object

- src/lang/de.json
- src/lang/en.json
- src/lang/fr.json
- src/lang/ja.json
- src/module/config.js
We are missing the Cold and Slashing damage type. 
Example: The Glaiad in AP 35 pg. 58:
`Melee iceblade +9 (1d8+6 C & S)`
> Added the `Cold & Slashing` damage type.

- gulpfile.js
- package.json
Updated gulp.js and package.json with copy action vs. symlink. Docker hates symlinks. Also added a buildDock and cleanDock command for easier usage and avoid impacting the current workflow.
> Update Gulp workflow for Docker

- scripts/comp_actor_cleaner.py
- scripts/comp_equipment_cleaner.py
- scripts/comp_equipment_id_migrator.py
3 scripts to make it easier to clean jsons for addition to compendiums
comp_actor_cleaner.py and comp_equipment_cleaner.py iterates through files in its directory and strips the files of "_id", "sort", and "exportSource" fields.
comp_equipment_id_migrator is more complex. It basically replaces old compendium items with the new modified items while preserving the "_id" of the old file and removing "sort", and "exportSource" in the new file.
> Python scripts for compendium contributors

- src/lang/de.json
- src/lang/en.json
- src/lang/fr.json
- src/lang/it.json
- src/lang/ja.json
- src/lang/pt-BR.json
- src/less/actors.less
- src/module/item/item.js
When you have a feat with an activation cost of none the label on the button is set to null leaving a thin and difficult-to-click line instead of a properly sized button. This PR sets the label to "Activate" to indicate that the feat can be activated while not indicating a cost as would normally be the case
> Small tweak for the activation button on active feats

- src/lang/de.json
- src/lang/en.json
- src/lang/fr.json
- src/lang/it.json
- src/lang/ja.json
- src/lang/pt-BR.json
- src/module/rules/actions/actor/calculate-classes.js
- src/module/rules/actions/item/calculate-save-dc.js
- src/template.json
- src/templates/items/class.html
Currently, spell DCs always default's to your key ability score. This merge incorporates the dropdown into the calculation, allowing Precogs to have an easy method of setting their spellcasting, instead of manually changing every spell. The priority is:
1.  The ability set in the spell
2.  The ability set in the spellcasting dropdown
3.  The class's key ability score
Also set the default save DC of feats to half level rather than full level as that is usually the default for class features.
> Add spellcasting ability selector to classes

- src/module/actor/mixins/actor-damage.js
Currently applying damage to a starship throws an error, saying ChoiceDialog is undefined. Adding an import fixes that and it behaves as expected.
> Fix applying damage to starships throwing an error

- src/items/equipment/clothing_everyday.json
Hi, small fix for an item : everyday clothing is 1 credit rather than 5.
See Archives of Nethys for reference : https://www.aonsrd.com/OtherItemsDisplay.aspx?ItemName=Everyday&Family=Clothing .
I can confirm that it's the same in the (French) Core Rulebook.
PS: Cooking the equipment db it looks like an item unrelated to this change gets removed : `Tool Kit, SF Armory`. From a quick glance it looks like it's because `Starfinder` is written in full now. Not sure what to do with it so I did not include it in the patch.
> Fix everyday clothing price

- src/items/spells/energy_ray.json
- src/items/spells/hazard.json
- src/items/spells/injury_echo.json
- src/items/spells/telekinetic_projectile.json
- src/lang/de.json
- src/lang/en.json
- src/lang/fr.json
- src/lang/it.json
- src/lang/ja.json
- src/lang/pt-BR.json
- src/module/actor/sheet/base.js
- src/module/item/item.js
- src/module/settings.js
Feeling productive this week! 😁
Added a system setting to enable scaling cantrips. Upon enabling, it'll edit the affected spells in the spells compendium.
I was going to add a check to startup to ensure the setting is being followed, but I was concerned about init times so I left that out, let me know if I should pursue that.
The formula used is admittedly a really ugly lookupRange one, I'll see if I can make a non-lookupRange one, but it'll still be a bit ugly. At least when expanded, a non-lookupRange formula won't show *all* the dice.
Also I just put the function in item.js, let me know if there's a better place for it.
> Scaling Cantrips variant rule

- src/lang/de.json
- src/lang/en.json
- src/lang/fr.json
- src/lang/it.json
- src/lang/ja.json
- src/lang/pt-BR.json
- src/module/config.js
- src/templates/apps/actor-flags.html
Removed solarian attunement from the special traits menu, and added a message to indicate there are no traits currently. 
Alternatively could remove the special traits menu entirely, but that would feel more impactful
> Remove solarian attunement from special traits

- src/less/starship.less
- src/module/actor/sheet/starship.js
Example:
Currently, Stunt doesn't display the full selections of stunts, but that's a separate underlying issue that currently exists on the Tippy tooltips, but I can address that separately.
> Clicking a Starship Action expands with the description

- src/module/actor/actor.js
- src/module/dice.js
- src/module/item/item.js
- src/templates/apps/add-edit-skill.html
Example:
I used flavor to implement this rather than the same method as attack's roll notes and damage, just because I couldn't figure out how that worked. Don't think it'll be a major issue in the implementation though.
> Skill notes

- src/module/item/item.js
Added a modifier that automatically adds to Archaic weapons that gives a -5 penalty to damage. Defaults to on (under the assumption that *most* enemies will have non-archaic armor), but can easily be toggled off under different circumstances.
> Give archaic weapons -5 damage

- src/items/equipment/backpack_consumer.json
- src/items/equipment/backpack_industrial.json
- src/items/equipment/null-space_chamber_mk_1.json
- src/items/equipment/null-space_chamber_mk_2.json
- src/items/equipment/null-space_chamber_mk_3.json
- src/items/equipment/starfinder_backpack.json
- src/module/actor/actor-inventory-utils.js
At the moment, a container migration trips if a container has any of the properties listed on line 955 of `actor-inventory-utils.js`, however, the container items in the compendium have some of those very properties, so I've removed them. 
The migration itself is still a bit problematic, as it doesn't work correctly if the items only have _some_ of the properties (see above 😉), and I may try to rectify that, but at least by changing the compendium JSONs the problem is no longer propagating.
> Migrate container item jsons as to not trip migration

- src/lang/en.json
- src/module/dice.js
Currently, when the skip dialog option is checked, shift-clicking a roll has no effect. It would be more intuitive if this setting instead acted as an inversion of the default behavior: showing the dialog on a shift-click. 
Closes #635
> Shift clicking a roll with the skip dialog option enabled will show the dialog window

- src/module/dice.js
- src/module/item/item.js
Currently, chat cards display an "undefined" on weapons with one damage section if the damage section has no name. This fixes that, and also removes the stray ":" caused by the same circumstances.
> Fix "undefined" on damage chat card if damage section has no name

- src/module/actor/mixins/actor-damage.js
Currently when applying 1/2 or 1.5x damage, you can end up dealing fractional damage, which is far from intended.
> Applying damage to a starship from a chat card obeys the Damage Rounding Advantage setting

- src/module/dice.js
- src/module/rolls/roll.js
First card is with the change, second is without.
`roll.formula` produces a cleaned up formula already, whereas `roll._formula` doesn't, so changing chat cards to use the former is a very easy fix.
> Prettify roll formulas on chat cards

- src/module/actor/actor-inventory-utils.js
- src/module/actor/sheet/base.js
- src/module/actor/sheet/character.js
- src/sfrpg.js
(remade PR because git decided we needed to bring this branch up to date with dev)
-Moved HTML template preload to init because sheets refuse to open otherwise.
-Explicitly add `isOpen` to containers, as it didn't seem to be adding before, fixing containers not opening or closing
-Refactor drag-drop to actor sheets to use Item.fromDropData, in the process removed some redundant logic, like if the item, came from a compendium or the sidebar. I've managed to get containers 99% functional, there are some minor bugs: some items refuse to stack, and the console spits out all sorts of messages about unknown items, even though the items are being moved fine.
> V10: Drag and Drop and other misc fixes

- src/module/canvas.js
- src/sfrpg.js
Loot actor sheets still behave oddly. This fix just restores dropping items to the canvas using a Hook instead of monkey patching core (which mainly consists of taking the existing functions, and rejigging them to work on the hook and on V10). Isolated it to its own function too.
> V10: Canvas Drop handler fixes

- src/module/actor/sheet/base.js
- src/module/apps/item-collection-sheet.js
- src/module/rules/actions/actor/calculate-bulk-and-wealth.js
- src/module/rules/actions/actor/calculate-encumbrance.js
- src/templates/actors/parts/actor-inventory-item.html
Currently total wealth shows NaN, and Bulk/the encumbrance bar is missing. This merge restores correct wealth calculation, and display of bulk and the encumbrance bar.
> V10: Fix bulk and wealth

- gulpfile.js
Closes #740 
Currently, `cook` replaces a journal's content with a single image page with the mystery man icon. This is because cook sets `img` for any document without `img` (which journals in V10 by definition don't have) to mystery man. This merge changes that so that if the current document is a journal, it is skipped.
> V10: Fix cook replacing journal pages with mystery man

- src/module/actor/sheet/character.js
- src/module/actor/sheet/hazard.js
- src/module/actor/sheet/starship.js
- src/module/actor/sheet/vehicle.js
- src/module/item/sheet.js
- src/sfrpg.js
- src/templates/actors/hazard-sheet-full.html
- src/templates/actors/hazard-sheet-limited.html
- src/templates/actors/parts/actor-biography.html
- src/templates/actors/starship-sheet-full.html
- src/templates/actors/starship-sheet-limited.html
- src/templates/actors/vehicle-sheet-full.html
- src/templates/actors/vehicle-sheet-limited.html
- src/templates/items/parts/item-description.html
Currently, text fields (such as the biography on an actor) always show the editor page, even after being saved. This merge fixes that by properly migrating to the new `editor` handlebar helper (and stripping out whatever `editorPlus` was, since the new `editor` handlebar helper does all `editorPlus` did). This is still using TinyMCE; we could migrate to ProseMirror if we want.
> V10: Fix text fields always showing the editor page

- src/module/actor/sheet/base.js
Currently, opening a character sheet throws an error that `data.items.sort` is not a function, because `data.items` is not an array. This change makes `data.items` an array. (character sheets still refuse to open, because we're trying to assign to getters with `hasAttack` and `hasDamage`. Not sure how it worked before, but it throws now 🤷‍♂️)
> Partly fix character sheets not opening after changes to base.js

- src/module/template-overrides.js
Currently, scenes with templates can refuse to load. This restores their normal functionality. Love a one-liner 😁
Closes #736 
Closes #748
> Fix Templates

- src/less/combat.less
- src/less/sfrpg.less
- src/module/combat/combat.js
The selector to select starship or vehicle combat currently doesn't show up.
> Restore combat type selector on combat tracker

- src/module/item/item.js
Didn't like using square brackets to declare object properties, I guess
Closes #765
> Fix item description chat cards throwing an error

- src/module/rules/actions/actor/calculate-damage-mitigation.js
Damage mitigation, and resistance, wouldn't process formula due to an issue with an incorrect reference to a variable in an object. This should fix that issue by referencing the right variable.
> Damage Mitigation Fix

- src/module/combat/combat.js
When a token in the combat tracker is hidden and it's turn comes up in the initiative this will stop it from announcing it to everyone automatically by whispering to the GM.
> Whisper chat cards for hidden combatants

- src/module/actor/actor.js
If HP, SP, or RP are updated to <0, or >Max, they will be clamped to that value.
> Clamp HP, SP and RP between 0 and Max

- src/lang/de.json
- src/lang/en.json
- src/lang/fr.json
- src/lang/it.json
- src/lang/ja.json
- src/lang/pt-BR.json
- src/less/apps.less
- src/module/apps/roll-dialog.js
- src/module/item/item.js
- src/module/item/sheet.js
- src/templates/chat/roll-dialog.html
- src/templates/items/parts/item-action.html
Damage sections can be grouped by number. You can only select one damage section in a given group. Un-grouped damage sections work as before. This allows for choices of damage, for example damaging cantrips.
~~TODO: Localisations and CSS~~
> Allow damage sections to share radio selections as Damage Groups

- src/less/roll.less
Removed color override from Damage dialog window. Allowing compatibility with UI mods.
> Damage dialog text color fix

- gulpfile.js
- src/items/conditions/invisible.json
Summary of changes here:
- Made errors red and successes green
- Formatting and consistency checking wasn't running due to bad object references, now run
- Remove SP checking on NPCs, they don't have stamina
- Updated some `token` references to `prototypeToken`
- Correct ID checking to correctly check for missing IDs
- Skip Invisible in conditions checking because it doesn't actually exist (may reverse later)
- Add IS to allowed sources
The result of these changes are that cook picks up 91 errors now which need to be fixed. See #855
> Added colours and fix error checking in cook

- gulpfile.js
Currently, it only returns the first instance
> Ensure searching for unlinked words in cook returns all instances in a file

- gulpfile.js
We only link to the first instance of a reference
> Change Cook to only flag instances of unlinked references the first time

- src/less/npc.less
- src/templates/actors/npc2-sheet.hbs
- Added +s to ability modifiers, initiative, and saves
- Remove +s from base saves
- Adjust margins of ability modifiers to account for extra space taken by the +
> Adjust signs on NPC stats

- src/less/variables.less
- src/templates/actors/parts/actor-inventory-item.hbs
- enabled item action buttons inside item collections
This was requested by @Iankid to make solar crystals work inside a Solar Weapon.
Just a more flexible approach to allow all items to have their buttons.
> add action buttons in item collections

- .eslintrc.json
- gulpfile.js
- package-lock.json
- package.json
**This merge adds JQuery and JSDOM as prerequisites.**
- Running `unpackPacks` as an NPM script now unpacks the db files directly from the user's foundry data path
- `unpackPacks` and `cook` now run `sanitizeJSON`, which performs the following:
- Removes  `sort`, `folder`, `effects`, `ownership`/`permissions`, `_stats` and non-essential `flags`,
- Trims whitespace from item names
- Replaces Forge URLs in images
- Strips out redundant AoN/PDF ids and classes (not entirely working currently, why this is drafted)
- Fixes fake links, replacing them with UUID links (and changed cook to look for UUID links)
- Runs what was previously `ensureTokenDefaults`
- Now automatically sets token size according to the actor (we had *a lot* of large+ actors still with 1x1 prototype tokens)
- A slew of …
> Add JSON Sanitisation to cook, and improve unpack

- src/less/actors.less
- src/less/character.less
-Make save larger to account for longer descriptors
-Remove the space for equipped on spellbook (Will require an update to Quick Insert to accommodate a 3rd button)
-Shrink action column
> Adjust spellbook column sizes

- src/items/class-features/entropic_strike_(su).json
Added + floor 1/2 vanguard level to strike damage.
The accounts for the special specialization that Vanguard have to their strike, in spite of the operative weapon type.
> Entropic Strike damage update

- src/module/apps/roll-dialog.js
- src/templates/chat/roll-dialog.hbs
This stops "1d6+ 4" from being shown as being calculated to "1d6 + 4"
> Silently fix whitespace on modifiers and damage parts

- src/module/apps/roll-dialog.js
- src/module/dice.js
- src/module/item/item.js
- src/module/rolls/rolltree.js
This change allows for macros and such to access the result of `actor.rollSkill` or `item.rollAttack` etc.
Also included some optimisations(?) to scaling spell logic
> Return the roll object on DiceSFRPG.d20Rolls

- src/module/actor/actor.js
- src/module/actor/sheet/base.js
- src/module/actor/sheet/hazard.js
- src/module/actor/sheet/starship.js
- src/module/actor/sheet/vehicle.js
- src/module/apps/item-collection-sheet.js
- src/module/item/item.js
- src/module/item/sheet.js
I'm amazed no one noticed inline values like [[@details.level.value]] haven't worked consistently since the start of V10
> Supply roll data to HTML enrichment, and refactor item chat data

- src/lang/de.json
- src/lang/en.json
- src/lang/fr.json
- src/lang/it.json
- src/lang/ja.json
- src/lang/pt-BR.json
- src/less/apps.less
- src/module/system/enrichers/base.js
- src/module/system/enrichers/browser.js
- src/module/system/enrichers/check.js
- src/sfrpg.js
***BREAKING***: `@Browser` now uses `()` instead of `<>` since the latter gets eaten in chat messages. It can be worked around by including spaces or `\` but ultimately that's bad UX so we should rip off this band-aid now.
> Add framework for repost buttons on inline buttons

- src/items/class-features/entropic_pool_(su).json
- src/items/class-features/exergy.json
- src/items/class-features/exergy_insight_(ex).json
- src/items/class-features/metabolic_stability_(ex).json
- src/items/class-features/mitigate_(ex).json
- src/items/class-features/reactive_(ex).json
- src/items/equipment/disintegration_lash_decimator.json
- src/items/equipment/disintegration_lash_eradicator.json
- src/items/equipment/disintegration_lash_executioner.json
- src/items/equipment/disintegration_lash_liquidator.json
- src/items/racial-features/stony_plates.json
Added pictures to: Entropic Pool, Exergy, Exergy Insight, Metabolic Stability, Mitigate, Reactive and Stony Plates.
Fixed ammunition on disintegration lash and added picture to them as well.
Linked Diehard feat on Metabolic Stability's description.
> Pictures, and minor fix on disintegration lash and Metabolic Stability

- src/module/item/item.js
Fixes the path to a container's contained wealth value. An error was being thrown when containers were clicked to expand, which this corrects.
> Quick fix for container wealth calculation

- src/less/apps.less
- src/module/actor/actor.js
- src/module/actor/mixins/actor-modifiers.js
- src/module/apps/modifier-app.js
- src/module/apps/roll-dialog.js
- src/module/canvas/ability-template.js
- src/module/item/item.js
- src/module/modifiers/modifier.js
- src/module/rules/closures/stack-modifiers.js
- src/templates/apps/modifier-app.hbs
-Ensure modifiers don't save damage sections or limit to if not applicable by refactoring to fieldsets
-Refactor getAllModifiers to use push, and to return a cached version if possible 
-Migrate modifier containers to UUIDs, and ensure they are not saved to DBs 
-Refactor modifiers to be stored in memory as SFRPGModifier class instances
> Refactor Modifiers to use DataModels

- src/module/combat/combat.js
Separates out difficulty add so that if difficulty is empty in any way that it won't attempt to add it as a classList add. This will prevent combat menu desync. Fixes #1261
> Guard against empty difficulty data

- src/module/rules/actions/actor/character/calculate-character-level.js
This replaces the previous PR #1275, which I accidentally based directly off my dev branch.
This preemptively fixes the tooltip on the character sheet identifying character class information for the Starfinder Enhanced classes introduced in https://github.com/foundryvtt-starfinder/foundryvtt-starfinder/pull/1273.
Before:
After:
> Fix character sheet tooltip for Enhanced classes

- src/module/migration.js
Hi there,
This should take care of it. If the damage isn't an array it's most likely in a good state and can be used without applying the migration.
> fix damage type migration idempotency

- src/sfrpg.js
Moved the structure defined in `game.sfrpg` to a variable definition `moduleStructure`, then passed that first to `globalThis`, then add `engine` and pass to `game.sfpg` in the init hook
> Add a globalThis to make class extension by modules easier

- src/module/actor/sheet/base.js
If a dropped item is clicked on and pulled into the inventory, it results in a "processedDroppedData", transfering the instance of the dropped object under "parsedDragData.items[0]". The item is not given as ItemCollection but as an object already, and by casting "toObject()" it simply breaks at this point. As such things can't be taken into the inventory. Removing that wrong command makes it work as intendet.
> Repaired "picking up dropped items"

- src/module/actor/sheet/base.js
This solution checks now if toObject is available, executes it if possible or takes the existing item instance transmitted.
As the purpose of the function is actually to transfer an item, the instance can be changed and/or preserved without issue. If this is still unwanted, a solution would be to use:
item = structuredClone(parsedDragData.items[0]);
> second try to fix "dropped item can't be picked up/moved to character"

- src/module/rules/actions/actor/starship/calculate-starship-targetlock.js
In src/module/rules/actions/actor/starship/calculate-starship-targetlock.js on lines 108 through 111 the bonus to targetLock was adding the shieldItem.armorBonus instead of the shieldItem.targetLockBonus.
> deflector shields were adding armorBonus instead of targetLockBonus

- src/module/item/item.js
This fixes calling `new Item.implementation(data)` throwing error `Cannot read properties of undefined (reading 'pack')`.
See: https://github.com/fantasycalendar/FoundryVTT-ItemPiles/issues/606
> Fixed item constructor context argument not being optional

- src/less/apps.less
- src/module/actor/mixins/actor-modifiers.js
- src/module/actor/sheet/base.js
- src/module/actor/sheet/character.js
- src/module/actor/sheet/drone.js
- src/module/apps/roll-dialog.js
- src/module/item/item.js
- src/module/item/sheet.js
- src/module/modifiers/modifier.js
- src/module/rules/closures/stack-modifiers.js
- Add a `toggle` method to `SFRPGModifier`
- Remove `container` in favour of passing the owning actor/item to the DataModel constructor, simplifying accessing them, and allowing for access to them without data prep
- Always re-calculate `max` during `_initialize`
- Remove active tab transition to eliminate flickering
> Refactor modifier toggling and parent propagation

- src/module/combat/combat.js
Fixes an issue in 0.27 where clicking the combat type switch button would erroneously call the routine to handle timed effects and throw an error.
> Fix bug preventing combat type switch

- src/module/actor/actor.js
- src/module/chat/chatbox.js
- src/module/item/item.js
roll has been deprecated in favor of rolls when doing ChatMessage.Create. When rolls:[] is not used the chat message will not flag itself as a roll when IsRoll is called which can break all kinds of functionality like DiceSoNice knowing there is a dice roll to render.
> Roll Deprecated (Fix for IsRoll and DiceSoNice integration)

- src/module/combat/combat.js
This fix allows having no pilot and also applies piloting bonus when rolling initiative
1) Set initiative to piloting bonus if no pilot
2) Include piloting bonus when rolling for initiative.
> Starship Combat Initiative Fixes

- src/templates/apps/choice-dialog.hbs
In the update for V12 using the selectOptions from https://foundryvtt.com/api/classes/client.HandlebarsHelpers.html#selectOptions the api does not play nice with existing code if you just pass an array of strings and pass that array as the choices.
This fix uses the valueAttr (documentation reads as nameAttr but is deprecated) to specify the value of the choices should also be the label/string used for display rather than the index  of the choice.
This makes it work again with all the relevant code
1) starship actions
2) npc crew
3) critical damage effect editing
> choice-dialog.hbs fix for array

- src/module/actor/actor.js
- src/module/config.js
- src/module/item/item.js
The original implementation of the default icons feature had a bug which caused a default icon to always be applied to an actor or item imported from a compendium, even if it had it's own unique icon selected. This update changes the behavior to first check if the actor/item's icon is the default mystery man or item bag, and only replace the icon if that is the case.
> Fix default icons always applied on import from compendium

- src/module/item/sheet.js
- src/module/modifiers/modifier.js
When not contained on a parent actor modifiers were throwing errors when attempting to toggle the modifier state using the checkbox.
With this change the toggle functionality should work when on a standalone item or in the compendium.
> Define modifiers as SFRPGModifier

- src/module/rules/actions/actor/starship/calculate-starship-frame.js
When calculating the turn value of a starship include modifiers from armor and ablative armor penalties.
Fixes [#692 ](https://github.com/foundryvtt-starfinder/foundryvtt-starfinder/issues/692)
> Include armor turn modifier

- .editorconfig
- .eslintrc.json
Git for Windows, by default, will automatically convert crlf line endings to lf for internal representation, then back again on checkout. (See the [`core.autocrlf`](https://git-scm.com/docs/git-config#Documentation/git-config.txt-coreautocrlf) option.) On my Linux machine the files are checked out with lf endings. My editor then reads `.editorconfig`, learns that it should use dos endings and writes the file with crlf endings. I then run `git diff` and learn that I have edited the entire file.
Without line end guidance, tools should default to using the OS's native line end, and then the repo leans on `autocrlf` to make that Just Work™.
As a note, to view info about the internal representations of the files, use `git ls-files --eol`.
Fixes #1392
> Remove explicit checks for dos newlines.

- src/module/combat/combat.js
Combat should start at round 1 not 0.
Also printing the phase every time we change the rounds just adds more chat cards. If the phase is changing print it otherwise don't.
#1441
> Start at round 1 not 0

- src/module/item/item.js
This closes #1153 
When processing items the feat type logic was incorrect. It was comparing the action type against the activation type.
> Update feat type

- src/module/actor/sheet/base.js
- src/module/actor/sheet/starship.js
- src/module/actor/sheet/vehicle.js
- src/module/canvas/canvas.js
Allows other data types (such as `JournalEntry`) to pass through the drop hook without causing an exception.
Closes #1394
> Ignore unhandled drop types.

- CONTRIBUTING.md
- gulpfile.js
- src/system.json
This switches the manifest URL to be linked to a `system.json` file included with the release, rather than in the `master` branch. This will require a copy of `system.json` to be attached to the release along with the zip file when releasing, so I've modified the `package` gulp command to copy it as well when making the release `.zip` file.
In addition, I've written up a detailed process for all the steps required to make a new release, so that can be followed step-by-step in the future (and act as the basis for setting up github actions to automate release steps in the future).
> Package release updates

- build/unpack.js
When running `npm run unpack` in terminal, it throws an error saying `limitToPack` is accessed before initialization. This tweak sets that variable explicitly to `null` to fix the error.
> Fix uninitialized variable error when doing `npm run unpack`

- src/module/item/mixins/item-capacity.js
A change to item-capacity.js to accept specifically null values broke reloading capacity weapons. This changes getCapacityItem() to specifically return only null's or an item not null's items or undefined.
> Only return a value or null not undefined.

- src/module/item/item.js
This fixes an issue where enabling the Scaling Cantrips setting caused those cantrips to stop working, because there was a close bracket missing from the end of the formulas.
> Fix broken scaling cantrips

- src/items/equipment/shadow_pistol_umbral.json
This changes the separator in the name of the umbral shadow pistol from a hyphen to a comma so that it matches up with the others.
> Fix name of "Shadow pistol, umbral" to make it consistent with the other shadow pistols

- static/templates/items/parts/item-modifiers.hbs
The values of these were showing up as blank on the modifiers tab because they were missing from the template.
> Fix weapon-category-attacks and weapon-category-damage being missing from item modifiers template

- src/module/item/item.js
This adds the spell school to the list of chat card properties so that it appears in the chat area when spells are being cast. This can be useful in certain situations (e.g. if you have Technomantic Talent)
> Display spell school on chat card

- src/module/actor/actor.js
This fixes an issue where "Unarmed strike" does not have "Proficient" ticked when automatically added to new characters
> Fix unarmed strike proficiency issue

- src/items/equipment/laser_pistol_aphelion.json
- src/items/equipment/laser_pistol_corona.json
- src/items/equipment/laser_pistol_parallax.json
- src/items/equipment/laser_pistol_perihelion.json
- src/items/equipment/laser_pistol_zenith.json
The icons folder contains a different coloured icon for each laser pistol, but all of them were set to the azimuth icon in the json. This changes the icon fields in the json so that the different coloured icons are actually used.
> Fix incorrect icons on laser pistols

- src/items/class-features/prismatic_nimbus_(su).json
The DC formula for Prismatic Nimbus was missing the @ symbols and the s from levels.
> Fix mistakes in prismatic nimbus DC formula

- src/items/starship-actions/swift_kick.json
Fixes a mistake in the tooltip of Swift Kick which says gunnery phase instead of engineering phase.
> Fix mistake in swift kick phase tooltip

- src/items/equipment/disposal_blade_advanced.json
- src/items/equipment/disposal_blade_tactical.json
- src/items/equipment/disposal_blade_ultrathin.json
- src/items/equipment/disposal_blade_zero-edge.json
The disposal blades are advanced melee weapons that don't have any range increment, but it was incorrectly set to 20 ft
> Remove range increment from disposal blades

- src/items/equipment/field_ration.json
Change the field ration into a consumable with 7 charges, one charge used per day.
This makes it possible to track ration usage.
> Consumable field rations

- src/items/equipment/eoxian_wrackstaff.json
Eoxian Wrackstaff is a hybrid item. This was being represented with a bold string in the description, and the property tick box was missing. I added the missing tick box and removed the now-superfluous string from the description.
> Fix hybrid property missing from Eoxian Wrackstaff

- src/items/equipment/junk_drone.json
- src/items/equipment/spy_drone.json
Junk Drone and Spy Drone are powered by batteries, capacity 20, usage 1/minute.
This sets the correct capacity and usage, and allows batteries to be attached and reloaded.
> Junk Drone and Spy Drone battery fix

- src/items/equipment/junk.json
- src/items/equipment/rubbish_cannon_heavy.json
- src/items/equipment/rubbish_cannon_light.json
- src/items/equipment/rubbish_cannon_standard.json
- src/module/config.js
- static/lang/de.json
- static/lang/en.json
- static/lang/fr.json
- static/lang/it.json
- static/lang/ja.json
- static/lang/pt-BR.json
- Fix icons
- Add missing space to Rubbish Cannon, Standard
- Add junk ammunition type and item
- Rubbish Cannons now uses junk ammo instead of flares
> Rubbish Cannon fixes

- src/items/equipment/junk_camouflage.json
The price of Junk Camouflage was set to 503 when it should be 50.
https://www.aonsrd.com/OtherItemsDisplay.aspx?ItemName=Junk%20Camouflage&Family=None
> Fix incorrect price of Junk Camouflage

- src/module/item/item.js
This fixes an issue where, when Scaling Cantrips is enabled, dragging the scaling cantrips onto the actor sheet causes them to have a broken formula because of a missing bracket.
PR #1516 fixed this issue for cantrips that already existed on the actor sheet when enabling the Scaling Cantrips setting. However it turns out there is a second copy of these formulas used when dropping cantrips onto the actor sheet from the compendium, and I missed those. This fixes the same mistake in the other copy.
> Fix scaling cantrips getting broken formula when dropping new cantrips onto the character or NPC sheet

- src/items/equipment/unarmed_strike.json
The "Weapon Is Equipment" tick box on the weapon properties editing form states that the box should be unchecked for natural weapons, however the "Unarmed strike" currently has this box ticked. This change fixes that issue.
> Unarmed strike is a natural weapon and should not be marked as equipment

- src/module/item/item.js
This fixes a bug where, when you have a consumable item with both "Consume on use" and "Destroy when empty" ticked, the last item is not destroyed when empty, and the player is just left with an unusable item in the inventory (this can be reproduced with Serum of Healing Mk 1).
I also rewrote the logic a little bit, because I found the original logic hard to follow when trying to fix this bug.
> Fix incorrect usage deduction for consumables such as serum of healing

- src/module/apps/roll-dialog.js
- src/module/dice.js
- src/module/rolls/rollnode.js
- static/templates/chat/roll-dialog.hbs
A common complaint from my players is that they get confused by long formulas with brackets and inline math functions that get shown on roll dialogs and chat cards.
The objective of this PR is to try to simplify many of these formulas earlier, so that the end user sees what they're expecting (e.g. for Weapon Focus they will see `+1` or `+2` rather than `+ternary(gte((3 - 2),3),2,1)`).
> Improved roll simplification

- vite.config.js
Disable parent minify, it was overriding the settings in plugins. This would result in class names being minimized and in some instances causing issues with code like CONFIG.Dice.rolls.unshift(SFRPGRoll); as it's already created messages in games with one name registered in chat messages and will change to CONFIG.Dice.rolls.unshift(Oe) which will then throw errors when chat messages look of SFRPGRoll or some other different minimized variable name.
> Update vite config

- src/module/actor/actor.js
- src/module/item/item.js
The RollNode.getRolledModifiers() 
return (variableRolledMods ?? []).reduce((map, mod) => {
map.set(mod.bonus._id, mod.bonus);
return map;
}, new Map());
this will overlap results with shared id's or no id resulting in only the last option being available.
> Fix starship roll options

- src/less/actors.less
- src/less/apps.less
- src/less/chat.less
- src/module/combat/combat.js
- src/module/system/settings.js
- src/module/tooltip.js
- src/sfrpg.js
- static/lang/de.json
- static/lang/en.json
- static/lang/fr.json
- static/lang/it.json
- static/lang/ja.json
- static/lang/pt-BR.json
CSS changes
- Updates to h2 and h3 because foundry caused them to inherit
- Removed text-wrap from actors skill-create
- Updated chat button margins and width
Combat
- Removed event listener from start combat button. This looks like it was attempting to prevent the default foundry start from running but it would have needed stopPropagation as well not preventDefault. Since we were allowing it to run anyways I removed the listener and simply trigger it off of combatStart as this will allow modules like combat carousel to actually run the sfrpg begin combat properly.
Settings
- Added new client chatNotificationDuration that allows users to override the base default 5 second dismiss timeout. 
Tooltips
- Copy aria-label over to the old tooltip attribute if tooltip is absent and aria-label is …
> More V13 changes

- .github/workflows/prerelease.yml
- .github/workflows/release.yml
Changes the draft/pre-release/latest release settings to be correct based on the type of workflow that runs. Additionally, for prereleases, sets the manifest link to download the specific version of the prerelease rather than latest (which would be incorrect for prerelease testing).
> fix draft release settings that are incorrect

- src/less/document-browser.less
- src/module/combat/combat.js
Resolves two issues:
1. Fixes document browser text color errors (sets all `<dt>` and `<dl>` tags to use black font color).
2. Replaces the janky manual html string manipulation that happened in initiative rolls with DOM manipulation, fixing incorrectly placed roll explanations
> Fixes for v13 beta issues spotted during testing

- build/cook.js
For some reason `await Promise.all(readPromises);` doesn't resolve `parsedFolders`, one of its constituent elements, before it is duplicated and passed to `createPack`. This causes an empty array to always be passed for the folders, so they never get created in the packed databases.
This PR forces the folders to be evaluated synchronously, and removes the duplication step since it seems unnecessary.
Resolves #1577
> Resolve `cook` not parsing folders correctly

- package-lock.json
Fixes #1580 via running `npm install` and updating `package-lock.json`, which seems like it wasn't synced when `package.json` was updated in the PR #1400
> fix package-lock with `npm install`

- CONTRIBUTING.md
- build/setup-intellisense.js
I'm not sure if it's specific to v13 or my installation (Windows 11), but I couldn't get `setupIntellisense` to work without telling it what kind of symbolic links to create (directories vs. files). This PR makes that change, and also updates the documentation to give instructions on the new method.
> Intellisense setup v13 fix

- src/module/dice.js
Resolves #839.
This moves critical effect display from damage rolls to attack rolls, ensuring it is shown even if an attack roll does not include critical damage.
> Move critical effect display to attack roll

- src/less/sheets.less
- static/lang/de.json
- static/lang/en.json
- static/lang/fr.json
- static/lang/it.json
- static/lang/ja.json
- static/lang/pt-BR.json
- static/templates/actors/drone-sheet.hbs
- static/templates/actors/parts/actor-movement-element.hbs
- static/templates/apps/movement-config.hbs
Resolves #798.
This will show the full set of speeds for an actor in the speed hover tooltip. In addition, shows the full set of speeds in drone's speed displays.
> Add full speed display to speed tooltip

- src/module/actor/actor-inventory-utils.js
- src/module/apps/item-collection-sheet.js
- src/module/canvas/canvas.js
- src/module/token/token-ruler.js
This is an attempt to get the dropping items on canvas to be a little more usable. 
Dropping items on the canvas will create an item collection with the new container svg as the image to give a better understanding of what is going on. 
The collection item will not be locked so it can be moved and or deleted directly.
There is an already existing bug that I am having issue locating that when you drop collections in collections sometimes they are not reproduced correctly nested on the target actor. It seems to create new items but with id's for the old items in the parents collection property. *Resolved by generating new id's for each item and updating contents references*
-Fix HUD crash on right click and unlock the token.
-Change image to new container image 
-Open collections two …
> ItemCollection fixes and changes

- src/less/apps.less
Fixes #1605 , toggles colors for inline check links based on whether dark or light theme is selected so they're legible in both cases.
> Fix legibility of journal in-line checks

- .github/workflows/pr_test.yml
Builds the system against each PR submitted. Primarily to ensure that any dependency changes or build process changes are validated against the automated build process on the github machines.
This is useful for PRs like #1565 that make changes to the build process that work fine locally, but have issues on the github linux build servers.
> Test to build system on PR submission

- src/module/rules/actions/item/calculate-skill-dc.js
- static/lang/de.json
- static/lang/en.json
- static/lang/es.json
- static/lang/fr.json
- static/lang/it.json
- static/lang/ja.json
- static/lang/pt-BR.json
- static/templates/items/parts/item-action.hbs
This changes the label from e.g. "DC [x] Perception Check" to "Perception Check" if a variable DC box is checked, allowing for the easy creation of feats and other actions that have variable DC skill checks.
> Allow items with variable DC skill checks by hiding skill check DC on the item card

- static/templates/actors/starship-sheet-full.hbs
This PR fixes a typo in the starship sheet template that stops the Critical Damage Weapons (Aft) role editor from opening.
> Fix typo in starship sheet template (WeaponsArrayAft -> weaponsArrayAft)

- src/module/rules/actions/actor/starship/calculate-starship-critical-status.js
Turrets currently ignore critical weapon system damage when rolling attacks. This PR fixes that issue by setting the modifier for turret weapons to the worst weapon array modifier.
> Fix turrets not being impacted by critical weapon system damage

- src/module/combat/combat.js
If a non-GM player opens the combat tracker while a combat exists, but before the first round of combat, the render hook currently tries to add event listeners to prev/next combat type buttons that don't exist for that non-GM player. This causes an error to be thrown:
This PR fixes the issue, preventing the error from appearing.
> Fix renderCombatTracker hook error

- src/less/apps.less
- src/module/actor/actor.js
- src/module/apps/ui/hotbar.js
- src/module/system/hotbar-macros.js
- src/sfrpg.js
- static/lang/de.json
- static/lang/en.json
- static/lang/es.json
- static/lang/fr.json
- static/lang/it.json
- static/lang/ja.json
- static/lang/pt-BR.json
- static/templates/ui/hotbar.hbs
This is a PR for several small hotbar fixes:
- During the upgrade to Foundry v13 the custom hotbar implementation (HotbarSFRPG) was disabled. This pull request makes it compatible with Foundry v13 and re-enables it.
- Fixed the hotbarDrop not working properly
- The tick/cross icon in the corner of macro buttons and the Active/Inactive tooltip label no longer appear for items which have instantaneous duration
> Fix hotbar

- src/items/equipment/syringe_spear_advanced.json
- src/items/equipment/syringe_spear_elite.json
- src/items/equipment/syringe_spear_paragon.json
- src/items/equipment/syringe_spear_tactical.json
- src/items/equipment/syringe_stick_hyper-pointed.json
- src/items/equipment/syringe_stick_sharp-pointed.json
- src/items/equipment/syringe_stick_standard.json
- src/items/equipment/syringe_stick_supreme-pointed.json
- src/items/equipment/syringe_stick_ultra-pointed.json
The item sets Syringe Stick and Syringe Spear are missing descriptions; this PR adds them.
> Fix missing descriptions on Syringe Stick and Syringe Spear

- src/items/class-features/expanded_cache_(su).json
The icon path for Expanded Cache (Su) incorrectly has `%20` in causing a 404 error. This PR fixes it.
> Fix icon of Expanded Cache (Su)

- src/module/combat/combat.js
The starship combat currently uses 0 as the turn number during phases where everyone acts simultaneously. The code calls this a "hidden turn". However, this is not actually hidden. Instead it just highlights the first starship in the combatants list. That ship also gets the combat ring around it on the hex grid. This is misleading, as it seems to suggest it's that specific ship's turn, rather than being a phase where everyone acts simultaneously.
This PR changes the turn value to null during these phases, which causes the UI to correctly not highlight anyone:
I also took the opportunity to tidy up startCombat vs begin, which removed an incorrect data update being sent that contradicted the changes being made here (instead of calling the begin method from the combatStart hook triggered by …
> Fix starship combat hidden turn

- src/items/equipment/capture_pole_domination-class.json
- src/items/equipment/needler_estoc_sharp-pointed.json
- src/items/equipment/plasma_guide_series-42.json
- src/items/equipment/plasma_guide_series-73.json
- src/items/equipment/plasma_ring_single-valve.json
- src/items/equipment/radcannon_rapid-decay.json
- src/items/equipment/shadow_pistol_umbral.json
- src/items/equipment/syringe_stick_ultra-pointed.json
- src/items/equipment/void_rifle_tomb-class.json
A total of 9 items have a hash character at the start of their critical effect strings, which as far as I can see doesn't seem to do anything, so this looks like a mistake to me. This PR removes the hashes.
> Remove the hash from the start of some the critical effect strings in the compendium

- src/module/dice.js
There is a typo in DiceSFRPG.createRoll where "advantage" and "disadvantage" are incorrectly capitalized as "Advantage" and "Disadvantage". As a result, when you click those buttons on rolls created via this method, they don't work. This PR fixes this issue.
> Fix advantage and disadvantage buttons not working when calling DiceSFRPG.createRoll
